const { chromium } = require('@playwright/test');
const assert = require('node:assert/strict');
(async () => {
 const browser = await chromium.launch({headless:true, args:['--no-sandbox']});
 for (const width of [360,390,412,430]) {
  const page = await browser.newPage({viewport:{width,height:844}, deviceScaleFactor:1});
  const errors=[]; page.on('pageerror', e=>errors.push(e.message));
  page.on('console', msg=>{if(msg.type()==='error') errors.push(msg.text());});
  const check = async label => {
   assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth), `${width} ${label} overflow`);
   assert.equal(await page.locator('button button').count(),0,'nested buttons');
   const small=await page.locator('button').evaluateAll(els=>els.filter(e=>{const r=e.getBoundingClientRect();return r.width && (r.width<44 || r.height<44)}).map(e=>e.textContent));
   assert.deepEqual(small,[],`${label} small targets`);
  };
  await page.goto('http://127.0.0.1:5173');
  await check('cabinet');
  await page.screenshot({path:`/tmp/cabinet-${width}.png`,fullPage:true});
  await page.getByRole('textbox',{name:'술 검색'}).fill('not-a-bottle');
  await page.getByText('조건에 맞는 술이 없어요.').waitFor();
  await page.getByRole('textbox',{name:'술 검색'}).fill('');
  await page.getByRole('button',{name:'와인',exact:true}).click();
  assert.equal(await page.locator('.shelf .bottle-item').count(),2);
  await page.getByRole('button',{name:'전체',exact:true}).click();
  await page.getByRole('button',{name:'The Balvenie DoubleWood 12',exact:true}).click();
  await check('detail'); await page.screenshot({path:`/tmp/detail-${width}.png`,fullPage:true});
  await page.getByRole('button',{name:'뒤로',exact:true}).click();
  await page.getByRole('button',{name:'기록',exact:true}).click();
  await check('history');
  await page.getByRole('button',{name:'The Macallan Sherry Oak 12',exact:true}).click();
  await page.getByText('완병 · 2026.08.21').waitFor();
  await page.getByRole('button',{name:'뒤로',exact:true}).click();
  await page.getByRole('heading',{name:'비워낸 기록'}).waitFor();
  await page.getByRole('button',{name:'페어링',exact:true}).click();
  assert.equal(await page.locator('.pairing-card').count(),1);
  await check('pairing');
  await page.getByRole('textbox',{name:'페어링할 음식'}).fill('치즈');
  await page.getByRole('button',{name:'추천',exact:true}).click();
  await page.locator('.pairing-card').click();
  await page.getByRole('button',{name:'뒤로',exact:true}).click();
  await page.getByRole('heading',{name:'음식과 한 잔'}).waitFor();
  await page.getByRole('textbox',{name:'페어링할 음식'}).fill('');
  await page.getByRole('button',{name:'추천',exact:true}).click();
  assert.equal(await page.locator('.pairing-card').count(),0);
  await page.getByRole('button',{name:'술 추가',exact:true}).click();
  await check('camera');
  await page.getByRole('button',{name:'예시 사진으로 촬영 체험'}).click();
  await page.getByRole('heading',{name:'어떤 제품인가요?'}).waitFor();
  await check('candidates');
  await page.locator('.candidate').first().click();
  await check('confirm');
  await page.getByRole('button',{name:'이 제품이 맞아요 · 술장에 추가'}).click();
  assert.equal(await page.locator('.shelf .bottle-item').count(),7);
  assert.equal(await page.locator('.shelf').count(),3);
  await check('saved cabinet');
  assert.deepEqual(errors,[]);
  console.log(`${width}px: all five flows, search/filter, 7th bottle, overflow and touch targets PASS`);
  await page.close();
 }
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
