const { chromium } = require('@playwright/test');
const assert = require('node:assert/strict');
const KEY = 'wine-wisky:cabinet:v1';
(async () => {
 const browser = await chromium.launch({headless:true, args:['--no-sandbox']});
 for (const width of [360,390,412,430]) {
  const page = await browser.newPage({viewport:{width,height:844}});
  const errors=[]; page.on('pageerror', e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:5173');
  await page.getByRole('button',{name:'술 추가',exact:true}).click();
  await page.getByRole('button',{name:'예시 제품 목록에서 선택'}).click();
  await page.locator('.candidate').first().click();
  await page.getByRole('textbox',{name:'제품명',exact:true}).fill('나의 테스트 위스키');
  await page.getByRole('button',{name:'이 제품이 맞아요 · 술장에 추가'}).click();
  await page.reload();
  assert.equal(await page.locator('.shelf .bottle-item').count(),7);
  await page.getByRole('button',{name:'나의 테스트 위스키',exact:true}).click();
  await page.getByRole('spinbutton',{name:'내 평점 (0~5)',exact:true}).fill('4.7');
  await page.getByRole('textbox',{name:'시음 메모'}).fill('꿀 향과 부드러운 피니시');
  await page.getByRole('button',{name:'시음 기록 저장'}).click();
  await page.getByText('평점과 메모를 저장했어요.').waitFor();
  await page.getByRole('button',{name:'다 마신 술로 기록'}).click();
  await page.getByRole('button',{name:'취소',exact:true}).click();
  await page.getByText('보유 중',{exact:true}).waitFor();
  await page.getByRole('button',{name:'다 마신 술로 기록'}).click();
  await page.getByRole('button',{name:'네, 다 마셨어요'}).click();
  await page.getByText('빈 병 기록에 남겼어요.').waitFor();
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.reload();
  assert.equal(await page.locator('.shelf .bottle-item').count(),6);
  await page.getByRole('button',{name:'기록',exact:true}).click();
  await page.getByRole('button',{name:'나의 테스트 위스키',exact:true}).click();
  assert.equal(await page.getByRole('spinbutton',{name:'내 평점 (0~5)',exact:true}).inputValue(),'4.7');
  assert.equal(await page.getByRole('textbox',{name:'시음 메모'}).inputValue(),'꿀 향과 부드러운 피니시');
  await page.getByRole('button',{name:'보유 술장으로 되돌리기'}).click();
  await page.reload();
  assert.equal(await page.locator('.shelf .bottle-item').count(),7);
  await page.getByRole('button',{name:'Johnnie Walker Black Label',exact:true}).click();
  await page.getByRole('button',{name:'다 마신 술로 기록'}).click();
  await page.getByRole('button',{name:'네, 다 마셨어요'}).click();
  await page.getByRole('button',{name:'뒤로',exact:true}).click();
  await page.getByRole('button',{name:'페어링',exact:true}).click();
  assert.equal(await page.locator('.pairing-card').count(),0);
  await page.evaluate(key => {
    const data=JSON.parse(localStorage.getItem(key));
    data.bottles=data.bottles.map(b=>({...b,status:'finished',finishedAt:'2026.10.02'}));
    localStorage.setItem(key,JSON.stringify(data));
  },KEY);
  await page.reload();
  assert.equal(await page.getByRole('button',{name:'자세히 보기'}).count(),0);
  assert.equal(await page.locator('.shelf .bottle-item').count(),0);
  await page.evaluate(key=>localStorage.setItem(key,JSON.stringify({version:1,bottles:[]})),KEY);
  await page.reload();
  assert.equal(await page.locator('.shelf .bottle-item').count(),0);
  await page.getByRole('button',{name:'기록',exact:true}).click();
  await page.getByText('아직 비워낸 병이 없어요.').waitFor();
  await page.evaluate(key=>localStorage.setItem(key,'{broken'),KEY);
  await page.reload();
  await page.getByRole('alert').waitFor();
  assert.equal(await page.evaluate(key=>localStorage.getItem(key),KEY),'{broken');
  await page.evaluate(key=>localStorage.removeItem(key),KEY);
  await page.reload();
  await page.getByRole('button',{name:'The Balvenie DoubleWood 12',exact:true}).click();
  await page.evaluate(()=>{Storage.prototype.setItem = () => {throw new DOMException('Full','QuotaExceededError')};});
  await page.getByRole('spinbutton',{name:'내 평점 (0~5)',exact:true}).fill('1');
  await page.getByRole('button',{name:'시음 기록 저장'}).click();
  await page.getByRole('alert').waitFor();
  assert.equal(await page.getByText('평점과 메모를 저장했어요.').count(),0);
  assert.equal(await page.locator('.stat-grid').getByText('★ 4.5',{exact:true}).count(),1);
  assert.deepEqual(errors,[]);
  console.log(width+'px: persistence, journal, finish/restore, pairing exclusion, empty state and storage failures PASS');
  await page.close();
 }
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
